server:
  port: 8080
  servlet:
    context-path: /bgi
log:
  file:
    path: C:\\Users\\Administrator\\Desktop\\auto\\
    suffix: .log
    timeStamp: yyyyMMdd
    startScript:
      - C:\\Program Files\\BetterGI\\BetterGI.exe startOneDragon
      - C:\\Program Files\\BetterGI\\BetterGI.exe --startGroups flower
    endScript: TASKKILL /F /IM BetterGI.exe /T
    closeSecond: 3
    event:
      - GROUP_END
      - DRAGON_END
logging:
  level:
    root: INFO
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 20